### PR TITLE
PLANET-5269: Fix footer on mobile

### PR DESCRIPTION
**Pull request by pablocubico**
Ref: https://jira.greenpeace.org/browse/PLANET-5269

### CODE REVIEW

**Comment by mleray** [comment]
@pablocubico I tested this on local, it looks pretty good 👍  But I think that the spacing between the links is still too small, I feel like it would be tricky to click on the right link (especially on mobile)! See screenshot:
Screenshot 2020-07-09 at 15 26 07

**Comment by pablocubico** [comment]
> @pablocubico I tested this on local, it looks pretty good 👍 But I think that the spacing between the links is still too small, I feel like it would be tricky to click on the right link (especially on mobile)! See screenshot:
> Screenshot 2020-07-09 at 15 26 07

Ah, yes, I went a few versions back and the space was still small, not sure what to do about it since Will is out for the week. Will go back a few versions more to check if it was taller before.

**Comment by pablocubico** [comment]
Hey @mleray and @comzeradd : I checked going back a few versions in the master theme repo, and the line height was as in this version. This just fixes the issue of the icons and its centering, I think we can merge it and make a new one about the line height (making sure Will oversees it).

**Comment by mleray** [comment]
Hey, I've added a comment to the ticket asking Will about the line height issue; since it's part of the ticket description and it's probably a quick fix I feel like it makes sense to solve this problem here! I know that @pablocubico is currently off but I can take over if needed 🙂

**Pull request merged**
