### PR TITLE
PLANET-5730 Footer: Reverse last child icon margin for RTL

### PR DESCRIPTION
**Pull request by comzeradd**
Ref: https://jira.greenpeace.org/browse/PLANET-5730

### CODE REVIEW

**Review by mleray — COMMENTED** [review]
Maybe a better approach for this would be to use the `margin-inline-end` [property](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-end)? Then we don't need to add custom RTL code 🙂

**Comment by comzeradd** [comment]
Ah nice! I didn't know about `margin-inline-end`. But this looks to add in between margins for all elements, even the last one. So we would still need an exception for `last-child` (and then reverse it for rtl) to align them in center.

But since the code is indeed a bit complex, I found another solution which I think simplifies things a bit. I amended the commit to only add margin on the icons that have another sibling on their left.

**Comment by mleray** [comment]
I've tested on local using just:
```
&:not(:last-child) {
  margin-inline-end: 16px;
}
```
and it seems to work for both RTL and LTR directions!

**Comment by comzeradd** [comment]
Indeed :pray: I probably have mixed up code from the previous state locally.

Commit amended

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
